### ISSUE TITLE
List of streams

### ISSUE THREAD

**Issue by ArturNadolski** [rewolt/openfm-api-crawler#4]
Hello,

Any chance for code example to get list of channels with stream links?
Group Name, Channel Name, Strem Link, Logo Url

**Comment by rewolt** [comment]
Hi,

For this project I used only my web browser with network tab in developer console to obtain specific API endpoints. If you need more data, I suggest you to do the same research.
Personally I never intended to create my own player or something like this, so I didn't looked for links to streams.
